server:
  port: 7001

#Eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  #是否向Eureka中心注册自己
    fetch-registry: false  #false,表示自己为注册中心
    service-url: #监控界面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

