server:
  port: 7003

#Eureka配置
eureka:
  instance:
    #hostname: localhost
    hostname: eureka-7003
  client:
    register-with-eureka: false  #是否向Eureka中心注册自己
    fetch-registry: false  #false,表示自己为注册中心
    service-url: #监控界面
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/

